AWSTemplateFormatVersion: "2010-09-09"
Description: Certificate Step Function ServiceCatalog product
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for ECS products.
  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
Resources:
  certstepfunction:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Certificate Step Function
      Description: This product builds a StateMachine which can be used as custom CF resource for certificate or DNS entry creation
      Owner:
        Ref: PortfolioProvider
      Distributor:
        Ref: PortfolioProvider
      SupportDescription: Operations Team
      SupportEmail: support@yourcompany.com
      AcceptLanguage: en
      SupportUrl: http://helpdesk.yourcompany.com
      ProvisioningArtifactParameters:
        - Description: Certificate Step Function
          Info:
            LoadTemplateFromURL:
              Fn::Sub: ${RepoRootURL}products/certificate-step-function.json
          Name: v1.0
  Associatenginxcf:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: PortfolioId
      ProductId:
        Ref: certstepfunction
  constraintnginxcf:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associatenginxcf
    Properties:
      PortfolioId:
        Ref: PortfolioId
      ProductId:
        Ref: certstepfunction
      RoleArn:
        Ref: LaunchConstraintARN
      Description:
        Ref: LaunchConstraintARN
Outputs:
  ProductId:
    Value:
      Ref: certstepfunction
