version: 0.2
phases:
    build:
        commands:
            - echo "S3 Upload Beginning"
            - export ACCID=$(aws sts get-caller-identity --query 'Account' | tr -d '"')
            - aws s3 sync . s3://$DEPLOY_BUCKET/ --delete --exclude "*" --include "*.json" --include "*.yml"
            - echo "S3 Upload Complete, updating cloudformation now..."
            - /bin/bash deploy/run-pipelineupdate.sh
            - /bin/bash deploy/run-cloudformationupdate.sh
    post_build:
        commands:
            - echo "Deploy complete"