AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline container project with orchestrator ServiceCatalog product
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for ECS products.
  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
Resources:
  PipelineWithOrchestrator:
    Type: 'AWS::ServiceCatalog::CloudFormationProduct'
    Properties:
      Name: Container Codepipeline with Orchestrator
      Description: This product builds a codepipeline project for container CI/CD that triggers an orchestrator step function
      Owner: !Ref PortfolioProvider
      Distributor: !Ref PortfolioProvider
      SupportDescription: Operations Team
      SupportEmail: support@yourcompany.com
      AcceptLanguage: en
      SupportUrl: 'http://helpdesk.yourcompany.com'
      ProvisioningArtifactParameters:
        - Description: CodePipeline project with orchestrator
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}products/pipeline-with-orchestrator.yml'
          Name: v1.0
  Associatenginxcf:
    Type: 'AWS::ServiceCatalog::PortfolioProductAssociation'
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref PipelineWithOrchestrator
  constraintnginxcf:
    Type: 'AWS::ServiceCatalog::LaunchRoleConstraint'
    DependsOn: Associatenginxcf
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref PipelineWithOrchestrator
      RoleArn: !Ref LaunchConstraintARN
      Description: !Ref LaunchConstraintARN
Outputs:
  ProductId:
    Value: !Ref PipelineWithOrchestrator
